name: Java CI with Security Scans

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven   # кешируем зависимости для ускорения

      - name: Build with Maven (skip tests for speed)
        run: mvn clean package -DskipTests

      # ---------- SAST (SpotBugs) ----------
      - name: Run SpotBugs (generate XML)
        run: mvn spotbugs:spotbugs

      - name: Convert SpotBugs XML to HTML
        run: |
          sudo apt-get update && sudo apt-get install xsltproc -y
          xsltproc ~/.m2/repository/com/github/spotbugs/spotbugs/4.9.4/spotbugs-4.9.4.xsl target/spotbugs.xml > target/spotbugs.html

      - name: Upload SpotBugs HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugs.html

      # ---------- SCA (Snyk / OWASP) ----------
      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: '1.1045.0'

      - name: Run Snyk test
        run: snyk test --all-projects --show-vulnerable-paths=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk Report (JSON)
        run: snyk test --json > snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json
